import SwiftSyntax
import SwiftSyntaxMacros

// `@State var color: float4 = .blue` becomes:
//
//   var color: float4 = .blue {
//     @storageRestrictions(initializes: _color)
//     init(initialValue) { _color = initialValue }
//     get { _color }
//     set { _color = newValue; self.__update_color() }
//   }
//   private var _color: float4
//
// The init accessor (SE-0400) is what lets the original `= .blue` survive on a property that
// now has accessors. `__update_color` is generated by `@Component`; expansion order does not
// matter, because all expansions are spliced into one buffer before name lookup runs.
public struct StateMacro {}

extension StateMacro: AccessorMacro {
  public static func expansion(
    of node: AttributeSyntax,
    providingAccessorsOf declaration: some DeclSyntaxProtocol,
    in context: some MacroExpansionContext
  ) throws -> [AccessorDeclSyntax] {
    guard let decl = declaration.as(VariableDeclSyntax.self) else {
      context.error("F5", "@State can only be applied to a property.", at: declaration)
      return []
    }
    let (property, error) = StateProperty.parse(decl)
    guard let property else {
      if let error { context.error(error.id, error.message, at: error.node) }
      return []
    }

    let storage = Naming.storage(property.name)
    let update = Naming.update(property.name)

    return [
      """
      @storageRestrictions(initializes: \(raw: storage))
      init(initialValue) {
        \(raw: storage) = initialValue
      }
      """,
      """
      get {
        \(raw: storage)
      }
      """,
      """
      set {
        \(raw: storage) = newValue
        self.\(raw: update)()
      }
      """,
      // In-place mutation. `self.items.append(x)` through get/set would copy the array out,
      // mutate the copy (triggering CoW) and store it back; yielding the storage avoids that.
      // The update runs after the yield returns, when the exclusive access has ended.
      """
      _modify {
        yield &\(raw: storage)
        self.\(raw: update)()
      }
      """,
    ]
  }
}

extension StateMacro: PeerMacro {
  public static func expansion(
    of node: AttributeSyntax,
    providingPeersOf declaration: some DeclSyntaxProtocol,
    in context: some MacroExpansionContext
  ) throws -> [DeclSyntax] {
    guard let decl = declaration.as(VariableDeclSyntax.self),
          let property = StateProperty.parse(decl).property
    else { return [] }   // the accessor expansion already diagnosed this

    let storage = Naming.storage(property.name)
    let guardName = Naming.requiresComponent(property.name)

    return [
      "private var \(raw: storage): \(property.type)",
      // Without this, forgetting @Component fails with "cannot find '__update_x' in scope".
      // With it, the error names the actual problem.
      """
      private func \(raw: guardName)() {
        let _: any \(raw: Naming.componentProtocol) = self
      }
      """,
    ]
  }
}
