@testable import MetalGraphicsLib
import Foundation
import XCTest

// The theme, exported for the web: `DesignSystemWeb/generated/` holds `tokens.json` (design tokens
// for claude.ai/design), `tokens.css` (the same as CSS variables, light and dark) and `icons.json`
// (the `ThemeIcon` glyphs) and `animated-icons.json` (the `AnimatedGlyph` specs). The web components in `DesignSystemWeb/` draw with nothing else, so
// the design-system project `/design-sync` pushes stays what `Theme+Presets.swift` says.
//
// This fails when the files are not what the theme exports now. After changing the theme:
//
//     RECORD_TOKENS=1 swift test --filter DesignTokenExportTests
//
// See DesignSystemWeb/README.md.

final class DesignTokenExportTests: XCTestCase {
  private static var generated: URL {
    URL(fileURLWithPath: #filePath)
      .deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
      .appendingPathComponent("DesignSystemWeb/generated")
  }

  func testGeneratedTokensMatchTheTheme() throws {
    let record = ProcessInfo.processInfo.environment["RECORD_TOKENS"] == "1"
    let files = [
      "tokens.json": DesignTokenExport.json(),
      "tokens.css": DesignTokenExport.css(),
      "icons.json": DesignTokenExport.icons(),
      "animated-icons.json": DesignTokenExport.animatedIcons(),
    ]
    for (name, contents) in files.sorted(by: { $0.key < $1.key }) {
      let url = Self.generated.appendingPathComponent(name)
      let existing = try? String(contentsOf: url, encoding: .utf8)
      guard !record, let existing else {
        try FileManager.default.createDirectory(at: Self.generated, withIntermediateDirectories: true)
        try contents.write(to: url, atomically: true, encoding: .utf8)
        if existing != contents {
          XCTFail("Recorded \(url.path). Look at it, then run again without RECORD_TOKENS.")
        }
        continue
      }
      guard existing != contents else { continue }
      let old = existing.split(separator: "\n", omittingEmptySubsequences: false)
      let new = contents.split(separator: "\n", omittingEmptySubsequences: false)
      let line = zip(old, new).enumerated().first { $0.element.0 != $0.element.1 }?.offset ?? min(old.count, new.count)
      XCTFail(
        """
        \(name) is not what the theme exports (line \(line + 1)):
          file:  \(line < old.count ? old[line] : "<end>")
          theme: \(line < new.count ? new[line] : "<end>")
        Run RECORD_TOKENS=1 swift test --filter DesignTokenExportTests.
        """
      )
    }
  }

  func testEveryRoleIsExportedInBothAppearances() {
    let css = DesignTokenExport.css()
    for role in ThemeColor.allCases {
      let name = "--mg-color-\(DesignTokenExport.kebab("\(role)")):"
      XCTAssertEqual(css.components(separatedBy: name).count - 1, 3, "\(name) in light, dark and the dark media query")
    }
  }
}

// MARK: - Export

enum DesignTokenExport {
  // Everything draws in JetBrains Mono with its ligatures, the web as the app (`TextFont.systemFamily`):
  // the design system ships it.
  static let sansStack = #""JetBrains Mono", ui-monospace, Menlo, monospace"#
  static let monoStack = #""JetBrains Mono", ui-monospace, Menlo, monospace"#

  private static let header = "Generated by DesignTokenExportTests from Theme+Presets.swift. Do not edit."
  private static let themes: [(name: String, theme: Theme)] = [("light", .light), ("dark", .dark)]

  // MARK: tokens.json (Design Tokens Community Group format)

  static func json() -> String {
    let typography = ThemeTypography.standard
    var root: [(String, JSON)] = [("$description", .string(header))]

    root.append(("color", .object(themes.map { name, theme in
      (name, .object(ThemeColor.allCases.map { role in ("\(role)", token("color", .string(hex(theme[role])))) }))
    })))
    root.append(("hue", .object(themes.map { name, theme in
      (name, .object(ThemeHue.allCases.map { hue in ("\(hue)", token("color", .string(hex(theme.palette[hue])))) }))
    })))
    root.append(("glass", .object(themes.map { name, theme in
      (name, .object(ThemeMaterial.allCases.map { role in
        let glass = theme[role]
        return ("\(role)", .object([
          ("blur", token("dimension", .string(px(glass.blurRadius * ShadowState.sigmaPerRadius)))),
          ("saturation", token("number", .number(glass.saturation))),
          ("tint", token("color", .string(hex(glass.tint)))),
          ("tintBottom", token("color", .string(hex(glass.tintBottom ?? glass.tint)))),
          ("rim", token("color", .string(hex(glass.rim)))),
          ("rimBottom", token("color", .string(hex(glass.rim.withAlpha(glass.rimBottom))))),
          ("fallback", token("color", .string(hex(glass.fallback)))),
        ]))
      }))
    })))
    root.append(("font", .object(
      [
        ("family", .object([
          ("sans", token("fontFamily", .string(sansStack))),
          ("mono", token("fontFamily", .string(monoStack))),
        ])),
      ] + fonts(typography).map { name, font in
        (name, token("typography", .object([
          ("fontFamily", .string(font.design == .monospaced ? "{font.family.mono}" : "{font.family.sans}")),
          ("fontSize", .string(px(font.size))),
          ("fontWeight", .number(Float(cssWeight(font.weight)))),
        ])))
      }
    )))
    root.append(("space", .object(spacing().map { name, value in (name, token("dimension", .string(px(value)))) })))
    root.append(("radius", .object(radii().map { name, value in (name, token("dimension", .string(px(value)))) })))
    root.append(("shadow", .object(themes.map { name, theme in
      (name, .object(shadows(theme).map { name, shadow in
        (name, token("shadow", .object([
          ("color", .string(hex(shadow.color))),
          ("offsetX", .string(px(shadow.x))),
          ("offsetY", .string(px(shadow.y))),
          ("blur", .string(px(shadow.radius * ShadowState.sigmaPerRadius * 2))),
          ("spread", .string("0px")),
        ])))
      }))
    })))
    root.append(("motion", .object(motion().map { name, animation in
      let (duration, easing) = transition(animation)
      return (name, token("transition", .object([
        ("duration", .string("\(duration)ms")),
        ("timingFunction", .string(easing)),
        ("delay", .string("0ms")),
      ])))
    })))

    root.append(("editor", .object(themes.map { name, theme in
      (name, .object(
        editorColors(theme.editor).map { key, color in (key, token("color", .string(hex(color)))) }
          + syntaxStyles(theme.editor).map { key, style in
            var value: [(String, JSON)] = []
            if let color = style.foreground { value.append(("color", .string(hex(color)))) }
            if let weight = style.weight { value.append(("fontWeight", .number(Float(cssWeight(weight))))) }
            if style.italic == true { value.append(("fontStyle", .string("italic"))) }
            return ("syntax.\(key)", token("typography", .object(value)))
          }
      ))
    })))

    return JSON.object(root).rendered() + "\n"
  }

  private static func token(_ type: String, _ value: JSON) -> JSON {
    .object([("$type", .string(type)), ("$value", value)])
  }

  // MARK: tokens.css

  static func css() -> String {
    let typography = ThemeTypography.standard
    var out = "/* \(header) */\n\n"

    out += ":root {\n"
    out += "  --mg-font-family-sans: \(sansStack);\n"
    out += "  --mg-font-family-mono: \(monoStack);\n"
    out += "  --mg-font-features: \"calt\" 1, \"liga\" 1;\n"
    for (name, font) in fonts(typography) {
      let family = font.design == .monospaced ? "var(--mg-font-family-mono)" : "var(--mg-font-family-sans)"
      out += "  --mg-font-\(kebab(name)): \(cssWeight(font.weight)) \(px(font.size)) \(family);\n"
      out += "  --mg-font-\(kebab(name))-size: \(px(font.size));\n"
      out += "  --mg-font-\(kebab(name))-weight: \(cssWeight(font.weight));\n"
    }
    for (name, value) in spacing() { out += "  --mg-space-\(name): \(px(value));\n" }
    for (name, value) in radii() { out += "  --mg-radius-\(name): \(px(value));\n" }
    for (name, animation) in motion() {
      let (duration, easing) = transition(animation)
      out += "  --mg-motion-\(name)-duration: \(duration)ms;\n"
      out += "  --mg-motion-\(name)-easing: \(easing);\n"
    }
    let editor = Theme.light.editor
    out += "  --mg-editor-line-height: \(px(editor.lineHeight ?? editor.font.size + editor.lineSpacing));\n"
    out += "  --mg-editor-line-spacing: \(px(editor.lineSpacing));\n"
    out += "  --mg-editor-inset-x: \(px(editor.textInset.x));\n"
    out += "  --mg-editor-inset-y: \(px(editor.textInset.y));\n"
    out += "  --mg-editor-gutter-min-width: \(px(editor.minGutterWidth));\n"
    out += "  --mg-editor-font: \(cssWeight(editor.font.weight)) \(px(editor.font.size)) var(--mg-font-family-mono);\n"
    out += "}\n\n"

    out += ":root,\n[data-mg-theme=\"light\"] {\n\(appearance(.light, indent: "  "))}\n\n"
    // `data-theme` too: a design-system page or canvas switches its theme that way.
    out += "[data-mg-theme=\"dark\"],\n[data-theme=\"dark\"] {\n\(appearance(.dark, indent: "  "))}\n\n"
    out += "@media (prefers-color-scheme: dark) {\n  :root:not([data-mg-theme=\"light\"]):not([data-theme=\"light\"]) {\n"
    out += appearance(.dark, indent: "    ")
    out += "  }\n}\n"
    return out
  }

  /// The variables that differ between light and dark.
  private static func appearance(_ theme: Theme, indent: String) -> String {
    var out = "\(indent)color-scheme: \(theme.appearance == .dark ? "dark" : "light");\n"
    for role in ThemeColor.allCases {
      out += "\(indent)--mg-color-\(kebab("\(role)")): \(rgba(theme[role]));\n"
    }
    for hue in ThemeHue.allCases {
      out += "\(indent)--mg-hue-\(kebab("\(hue)")): \(rgba(theme.palette[hue]));\n"
    }
    for role in ThemeMaterial.allCases {
      let glass = theme[role], name = "--mg-glass-\(kebab("\(role)"))"
      out += "\(indent)\(name)-blur: \(px(glass.blurRadius * ShadowState.sigmaPerRadius));\n"
      out += "\(indent)\(name)-saturation: \(number(glass.saturation));\n"
      out += "\(indent)\(name)-tint: \(rgba(glass.tint));\n"
      out += "\(indent)\(name)-tint-bottom: \(rgba(glass.tintBottom ?? glass.tint));\n"
      out += "\(indent)\(name)-rim: \(rgba(glass.rim));\n"
      out += "\(indent)\(name)-rim-bottom: \(rgba(glass.rim.withAlpha(glass.rimBottom)));\n"
      out += "\(indent)\(name)-fallback: \(rgba(glass.fallback));\n"
    }
    for (name, shadow) in shadows(theme) {
      // A CSS blur radius is twice the Gaussian's standard deviation.
      let blur = shadow.radius * ShadowState.sigmaPerRadius * 2
      out += "\(indent)--mg-shadow-\(name): \(px(shadow.x)) \(px(shadow.y)) \(px(blur)) \(rgba(shadow.color));\n"
    }
    for (name, color) in editorColors(theme.editor) {
      out += "\(indent)--mg-editor-\(kebab(name)): \(rgba(color));\n"
    }
    for (name, style) in syntaxStyles(theme.editor) {
      let v = "--mg-syntax-\(kebab(name))"
      if let color = style.foreground { out += "\(indent)\(v): \(rgba(color));\n" }
      if let background = style.background { out += "\(indent)\(v)-background: \(rgba(background));\n" }
      if let weight = style.weight { out += "\(indent)\(v)-weight: \(cssWeight(weight));\n" }
      if style.italic == true { out += "\(indent)\(v)-style: italic;\n" }
    }
    return out
  }

  // MARK: icons.json

  static func icons() -> String {
    JSON.object(ThemeIcon.allCases.map { ("\($0)", .string($0.svg)) }).rendered() + "\n"
  }

  // MARK: animated-icons.json

  /// The animated glyphs as the template writes them: each glyph's box, stroke, triggers, markup
  /// and CSS, the shared rules and keyframes, and the spring as CSS `linear()`, sampled as the
  /// template's `spring()` samples it. The web's `AnimatedIcon` injects them as they are.
  static func animatedIcons() -> String {
    let glyphs = AnimatedGlyph.allCases.map { glyph -> (String, JSON) in
      let s = glyph.source
      var o: [(String, JSON)] = [
        ("box", .array([.number(s.box.x), .number(s.box.y)])),
        ("weight", .number(s.weight)),
        ("triggers", .array(s.triggers.map { .string($0.rawValue) })),
      ]
      if let state = s.state { o.append(("state", .string(state))) }
      if s.defaultActive { o.append(("defaultActive", .bool(true))) }
      if !s.component.isEmpty { o.append(("component", .string(s.component))) }
      o.append(("markup", .string(s.markup)))
      o.append(("css", .array(s.css.map(JSON.string))))
      if !s.morphs.isEmpty { o.append(("morphs", .object(s.morphs.sorted { $0.key < $1.key }.map { ($0.key, .string($0.value)) }))) }
      if !s.snippetCSS.isEmpty { o.append(("snippetCss", .array(s.snippetCSS.map(JSON.string)))) }
      if let p = s.pointer { o.append(("pointer", .array([.number(p.x), .number(p.y)]))) }
      return (glyph.rawValue, .object(o))
    }
    let (linear, ms) = springLinear()
    return JSON.object([
      ("spring", .object([
        ("stiffness", .number(GlyphEasing.springStiffness)), ("damping", .number(GlyphEasing.springDamping)),
        ("ms", .number(Float(ms))), ("linear", .string(linear)),
      ])),
      ("morphSpring", .object([("stiffness", .number(MorphSpring.stiffness)), ("damping", .number(MorphSpring.damping))])),
      ("base", .array(AnimatedGlyphSource.base.map(JSON.string))),
      ("keyframes", .object(AnimatedGlyphSource.keyframes.map { ($0.name, .string($0.body)) })),
      ("glyphs", .object(glyphs)),
    ]).rendered() + "\n"
  }

  /// The template's `spring(210, .38)`: stepped at 2 kHz until it settles, sampled at 45 points.
  private static func springLinear() -> (String, Int) {
    let k = Double(GlyphEasing.springStiffness), c = 2 * Double(GlyphEasing.springDamping) * k.squareRoot(), dt = 1.0 / 2000
    var x = 0.0, v = 0.0, t = 0.0, settle = 0.0
    var samples: [Double] = []
    while t < 3 {
      v += (-k * (x - 1) - c * v) * dt; x += v * dt; t += dt; samples.append(x)
      if abs(x - 1) < 0.001 && abs(v) < 0.01 {
        if settle == 0 { settle = t }
        if t - settle > 0.02 { break }
      } else {
        settle = 0
      }
    }
    let n = 44
    var out: [String] = []
    for i in 0...n {
      let value = i == 0 ? 0 : i == n ? 1 : samples[min(samples.count - 1, Int((Double(i) / Double(n) * Double(samples.count - 1)).rounded()))]
      // as JavaScript's +x.toFixed(3) prints it
      let r = (value * 1000).rounded() / 1000
      out.append(r == r.rounded() ? String(Int(r)) : String(r))
    }
    return ("linear(\(out.joined(separator: ", ")))", Int((t * 1000).rounded()))
  }

  // MARK: The theme, as named lists

  private static func fonts(_ t: ThemeTypography) -> [(String, TextFont)] {
    [
      ("largeTitle", t.largeTitle), ("title", t.title), ("title2", t.title2), ("title3", t.title3),
      ("headline", t.headline), ("body", t.body), ("callout", t.callout), ("subheadline", t.subheadline),
      ("footnote", t.footnote), ("mono", t.mono), ("monoSmall", t.monoSmall),
    ]
  }

  private static func spacing() -> [(String, Float)] {
    let s = ThemeSpacing()
    return [
      ("xxxs", s.xxxs), ("xxs", s.xxs), ("xs", s.xs), ("sm", s.sm), ("md", s.md),
      ("lg", s.lg), ("xl", s.xl), ("xxl", s.xxl), ("xxxl", s.xxxl),
    ]
  }

  private static func radii() -> [(String, Float)] {
    let r = ThemeRadii()
    return [("xs", r.xs), ("sm", r.sm), ("md", r.md), ("lg", r.lg), ("xl", r.xl)]
  }

  /// The code editor's surfaces, in `EditorTheme` order; diagnostics by severity.
  private static func editorColors(_ e: EditorTheme) -> [(String, float4)] {
    var colors: [(String, float4)] = [
      ("background", e.background), ("foreground", e.foreground), ("caret", e.caret), ("selection", e.selection),
      ("inactiveSelection", e.inactiveSelection), ("currentLine", e.currentLine ?? .clear),
      ("gutterBackground", e.gutterBackground), ("gutterForeground", e.gutterForeground),
      ("gutterCurrentLine", e.gutterCurrentLine), ("gutterSeparator", e.gutterSeparator ?? .clear),
      ("markedText", e.markedText), ("searchMatch", e.searchMatch), ("currentSearchMatch", e.currentSearchMatch),
      ("bracketMatch", e.bracketMatch),
    ]
    for (i, severity) in ["hint", "info", "warning", "error"].enumerated() where i < e.diagnosticColors.count {
      colors.append(("diagnostic\(severity.prefix(1).uppercased())\(severity.dropFirst())", e.diagnosticColors[i]))
    }
    return colors
  }

  /// The syntax styles by token name, the ones the theme sets.
  private static func syntaxStyles(_ e: EditorTheme) -> [(String, SpanStyle)] {
    let tokens: [(String, TextToken)] = [
      ("keyword", .keyword), ("type", .type), ("function", .function), ("string", .string), ("number", .number),
      ("comment", .comment), ("attribute", .attribute), ("directive", .directive), ("operatorSymbol", .operatorSymbol),
      ("punctuation", .punctuation), ("variable", .variable), ("constant", .constant), ("heading1", .heading1),
      ("emphasis", .emphasis), ("strong", .strong), ("code", .code), ("link", .link), ("markup", .markup),
      ("quote", .quote), ("listMarker", .listMarker), ("strikethrough", .strikethrough), ("output", .output),
      ("error", .error), ("prompt", .prompt), ("success", .success),
    ]
    return tokens.compactMap { name, token in e[token].map { (name, $0) } }
  }

  private static func shadows(_ theme: Theme) -> [(String, ThemeShadow)] {
    let s = theme.shadows
    return [("control", s.control), ("popover", s.popover), ("sheet", s.sheet), ("float", s.float)]
  }

  private static func motion() -> [(String, UIAnimation)] {
    let m = ThemeMotion()
    return [
      ("hover", m.hover), ("interaction", m.interaction), ("dock", m.dock),
      ("navigation", m.navigation), ("presentation", m.presentation),
    ]
  }

  /// A duration in milliseconds and a CSS easing that draws the same curve: the cubic Béziers of
  /// `UIAnimation.ease`'s cubic polynomials, and a spring sampled into `linear()` until it settles.
  private static func transition(_ animation: UIAnimation) -> (Int, String) {
    let ms = Int((animation.duration * 1000).rounded())
    switch animation.curve {
    case .linear: return (ms, "linear")
    case .easeIn: return (ms, "cubic-bezier(0.32, 0, 0.67, 0)")
    case .easeOut: return (ms, "cubic-bezier(0.33, 1, 0.68, 1)")
    case .easeInOut: return (ms, "cubic-bezier(0.65, 0, 0.35, 1)")
    case .spring(let omega, let zeta):
      let step: Float = 1 / 60
      var samples: [Float] = [], t: Float = 0
      while true {
        let (value, done) = UIAnimation.spring(omega: omega, zeta: zeta, from: .zero, to: float4(1, 0, 0, 0), velocity: .zero, t: t)
        samples.append(done ? 1 : value.x)
        if done || t > 3 { break }
        t += step
      }
      return (Int((t * 1000).rounded()), "linear(\(samples.map { number($0) }.joined(separator: ", ")))")
    case .keyframes: return (ms, "linear")
    }
  }

  // MARK: Formatting

  static func kebab(_ name: String) -> String {
    var out = ""
    for (i, c) in name.enumerated() {
      if c.isUppercase || (c.isNumber && i > 0 && !(out.last?.isNumber ?? false)) { out += "-" }
      out += c.lowercased()
    }
    return out
  }

  private static func cssWeight(_ weight: TextFont.Weight?) -> Int {
    switch weight ?? .regular {
    case .ultraLight: 100
    case .thin: 200
    case .light: 300
    case .regular: 400
    case .medium: 500
    case .semibold: 600
    case .bold: 700
    case .heavy: 800
    case .black: 900
    }
  }

  private static func number(_ value: Float) -> String {
    let rounded = (Double(value) * 1000).rounded() / 1000
    if rounded == rounded.rounded() { return String(Int(rounded)) }
    var s = String(format: "%.3f", rounded)
    while s.hasSuffix("0") { s.removeLast() }
    return s
  }

  private static func px(_ value: Float) -> String { "\(number(value))px" }

  private static func channels(_ c: float4) -> (Int, Int, Int) {
    func byte(_ v: Float) -> Int { Int((min(max(v, 0), 1) * 255).rounded()) }
    return (byte(c.x), byte(c.y), byte(c.z))
  }

  /// `#RRGGBB`, or `#RRGGBBAA` when not opaque.
  private static func hex(_ c: float4) -> String {
    let (r, g, b) = channels(c)
    let alpha = Int((min(max(c.w, 0), 1) * 255).rounded())
    return alpha == 255
      ? String(format: "#%02X%02X%02X", r, g, b)
      : String(format: "#%02X%02X%02X%02X", r, g, b, alpha)
  }

  /// `#RRGGBB` when opaque, else `rgba(r, g, b, a)`, which reads better in a stylesheet.
  private static func rgba(_ c: float4) -> String {
    let (r, g, b) = channels(c)
    return c.w >= 1 ? hex(c) : "rgba(\(r), \(g), \(b), \(number(c.w)))"
  }
}

/// JSON with its keys in the order given, so the files read like the theme.
private indirect enum JSON {
  case string(String)
  case number(Float)
  case bool(Bool)
  case array([JSON])
  case object([(String, JSON)])

  func rendered(_ indent: String = "") -> String {
    switch self {
    case .string(let s):
      let data = try! JSONSerialization.data(withJSONObject: s, options: [.fragmentsAllowed, .withoutEscapingSlashes])
      return String(decoding: data, as: UTF8.self)
    case .number(let n):
      let rounded = (Double(n) * 1000).rounded() / 1000
      return rounded == rounded.rounded() ? String(Int(rounded)) : String(rounded)
    case .bool(let b):
      return b ? "true" : "false"
    case .array(let items):
      // Numbers and short leaves on one line; objects one per line.
      if items.allSatisfy({ if case .object = $0 { false } else { true } }) {
        return "[" + items.map { $0.rendered() }.joined(separator: ", ") + "]"
      }
      let inner = indent + "  "
      return "[\n" + items.map { inner + $0.rendered(inner) }.joined(separator: ",\n") + "\n\(indent)]"
    case .object(let members) where members.isEmpty:
      return "{}"
    case .object(let members):
      let inner = indent + "  "
      let body = members.map { "\(inner)\(JSON.string($0.0).rendered()): \($0.1.rendered(inner))" }
      return "{\n" + body.joined(separator: ",\n") + "\n\(indent)}"
    }
  }
}
