import MetalGraphicsLib
import ReactiveUI

struct DemoItem : Identifiable {
  let id = UUID()
  let color: float4
}

// One row, as its own component.
//
// Rows cannot be inlined into `onCreate`: a row owns state (`hovered`) and state needs an owner
// the macro can generate against. Extracting it into a nested `@Component` is the sanctioned
// factoring — from `ListDemo`'s side `RowView(item:onRemove:)` is just a constructor call, and
// `RowView` resolves its own reactivity at compile time.
@Component
final class RowView : SingleChildElement {
  let item: DemoItem
  let onRemove: (DemoItem.ID) -> Void

  @State var hovered: Bool = false

  init(item: DemoItem, onRemove: @escaping (DemoItem.ID) -> Void) {
    self.item = item
    self.onRemove = onRemove
    super.init()
  }
  
  @UIElementBuilder var body: [UIElement] {
    Rectangle(self.hovered ? .black : self.item.color)
      .frame(width: 60, height: 24)
      .onHover { isHovered, _ in
        self.hovered = isHovered
      }
      .onTap { _ in
        self.onRemove(self.item.id)
      }
  }
}

// Shows how state reaches the screen: one @State array drives both lists, rows keep their own
// state across a shuffle, and values read inside element arguments update without a rebuild.
//
// Buttons, left to right: green appends, blue inserts at the front, red removes the last row,
// black shuffles (same items, new order), white clears, grey toggles the spacing.
@Component
final class ListDemo : SingleChildElement {
  private static let palette: [float4] = [
    .red, .green, .blue,
    .init(1, 0.8, 0.2, 1),    // amber
    .init(0.6, 0.3, 0.9, 1),  // purple
    .init(0.2, 0.8, 0.8, 1),  // teal
  ]

  @State var spacing: Float = 6
  @State var items: [DemoItem] = [
    .init(color: .red),
    .init(color: .green),
    .init(color: .blue),
  ]

  // Buttons are inlined: their colours are constant and they own no state, so there is
  // nothing for a nested component to hold.
  @UIElementBuilder var body: [UIElement] {
    VStack(alignment: .leading, spacing: 12) {
      HStack(spacing: 6) {
        Rectangle(.green).frame(width: 24, height: 24)
          .onTap { _ in self.append() }
        Rectangle(.blue).frame(width: 24, height: 24)
          .onTap { _ in self.insertFirst() }
        Rectangle(.red).frame(width: 24, height: 24)
          .onTap { _ in self.removeLast() }
        Rectangle(.black).frame(width: 24, height: 24)
          .onTap { _ in self.shuffle() }
        Rectangle(.white).frame(width: 24, height: 24)
          .onTap { _ in self.clear() }
        Rectangle(.init(0.5, 0.5, 0.5, 1)).frame(width: 24, height: 24)
          .onTap { _ in self.toggleSpacing() }
      }

      // Read inside an element argument, so only this frame's size updates.
      Rectangle(.blue)
        .frame(width: Float(self.items.count) * 24, height: 6)

      // Two lists over one collection; both follow every change.
      VList(spacing: self.spacing, items: self.items) { item in
        RowView(item: item, onRemove: { id in self.remove(id) })
      }
//      HList(spacing: self.spacing, items: self.items) { item in
//        RowView(item: item, onRemove: { id in self.remove(id) })
//      }

      // Read in a condition, so emptying the collection swaps this branch in.
      if self.items.isEmpty {
        Rectangle(.green).frame(width: 60, height: 60)
      }
    }
  }

  // MARK: - Actions

  // `appendItems` / `insertItems` / `removeItems` / `replaceItems` are generated by
  // @Component from `@State var items`. They exist so the call site can name the operation:
  // an append becomes one `insertChild` in each list, where a plain `self.items = …` would
  // have to rebuild every row.

  func append() {
    self.items.append(.init(color: Self.palette.randomElement() ?? .red))
  }

  func insertFirst() {
    self.items.insert(.init(color: Self.palette.randomElement() ?? .red), at: 0)
  }

  func removeLast() {
    self.items.removeLast()
  }

  func remove(_ id: DemoItem.ID) {
    self.items.removeAll(where: { $0.id == id })
  }

  // A reorder is not an incremental operation, so this takes the full-rebuild path \u{2014} and
  // every row still keeps its element, and with it its own state, through `elementsById`.
  func shuffle() {
    self.items = self.items.shuffled()
  }

  func clear() {
    self.items.removeAll(keepingCapacity: true)
  }

  func toggleSpacing() {
    self.spacing = self.spacing == 6 ? 20 : 6
  }
}
